permalink: /blog/:title/
# SASS
sass:
  style: compressed
  
# Site Settings (Meta placeholders)
site-keywords: "developer, svelte, jekyll, portfolio"
site-image: "https://github.com/harsh98trivedi/EchoFolio/raw/master/assets/img/meta.jpg"

author-name: "Harsh Trivedi"
google-analytics: "G-45C37D3GB5"

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - vite.config.js
  - src
  - README.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-workbox-plugin
  - jekyll-turbo

# Workbox Configuration
workbox:
  sw_src_filepath: _includes/sw.js # Optional: Path to your custom SW template
  sw_dest_filename: sw.js # Destination filename
  precache_glob_directory: _site
  precache_glob_patterns:
    - "**/*.{html,js,css,woff,woff2}"
    - "assets/img/*.{jpg,png,svg,webp}"
  precache_glob_ignores:
    - "sw.js"
    - "404.html"


# Jekyll Compress HTML Configuration
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
